term.clear()
print("bir0fetch:")
print("-----------------")
print("running: ", os.version())
print("computer id: ", os.getComputerID())
print("computer label: ", os.getComputerLabel())
print("computer has been running for: ", os.clock())
print("-----------------")
term.setCursorPosition(1, 7)
term.setTextColour(colours.black)
print("B")
term.setCursorPosition(2, 7)
term.setTextColour(colours.white)
print("W")
term.setCursorPosition(3, 7)
term.setTextColour(colours.red)
print("R")
term.setCursorPosition(4, 7)
term.setTextColour(colours.green)
print("G")
term.setCursorPosition(5, 7)
term.setTextColour(colours.blue)
print("B")
term.setCursorPosition(6, 7)
term.setTextColour(colours.pink)
print("P")
print("-----------------")
