term.clear()
print("birfetch:")
print("-----------------")
print("running: ", os.version())
print("computer id: ", os.getComputerID())
if os.getComputerLabel() == nil then
    print("computer label: ", os.getComputerLabel())
else
    print("computer label: n/a")
end
print("computer has been running for: ", os.clock())
print("-----------------")
term.setCursorPos(1, 7)
term.setTextColour(colours.black)
print("B")
term.setCursorPos(2, 7)
term.setTextColour(colours.white)
print("W")
term.setCursorPos(3, 7)
term.setTextColour(colours.red)
print("R")
term.setCursorPos(4, 7)
term.setTextColour(colours.green)
print("G")
term.setCursorPos(5, 7)
term.setTextColour(colours.blue)
print("B")
term.setCursorPos(6, 7)
term.setTextColour(colours.pink)
print("P")
term.setCursorPos(1, 8)
print("-----------------")
