term.clear()
print("birfetch:")
print("-----------------")
print("running: ", os.version())
print("computer id: ", os.getComputerID())
if not os.getComputerLabel() == nil then
    print("computer label: ", os.getComputerLabel())
else
    print("computer label: N/A")
end
print("computer has been running for: ", os.clock())
print("-----------------")
print("colour display:")
term.setTextColour(colours.black)
print("B")
term.setTextColour(colours.white)
print("W")
term.setTextColour(colours.red)
print("R")
term.setTextColour(colours.green)
print("G")
term.setTextColour(colours.blue)
print("B")
term.setTextColour(colours.pink)
print("P")
term.setTextColour(colours.white)
print("-----------------")
